// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_bpk6Vx8fhlHuWIaCsOMm6XHgJxB2SI',
    appId: '1:238119266452:web:b730cb86fb8288b52eac81',
    messagingSenderId: '238119266452',
    projectId: 'sebelumuts-2be00',
    authDomain: 'sebelumuts-2be00.firebaseapp.com',
    databaseURL: 'https://sebelumuts-2be00-default-rtdb.firebaseio.com',
    storageBucket: 'sebelumuts-2be00.firebasestorage.app',
    measurementId: 'G-4Q615JSE9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR0lRLWueGxtb86l2DIxL85E1f-TDIrAo',
    appId: '1:238119266452:android:3b7bee28ebe5777a2eac81',
    messagingSenderId: '238119266452',
    projectId: 'sebelumuts-2be00',
    databaseURL: 'https://sebelumuts-2be00-default-rtdb.firebaseio.com',
    storageBucket: 'sebelumuts-2be00.firebasestorage.app',
  );
}
